[package]
name = "transparent"
version = "0.1.1"
description = "A crate for running processes on a virtual desktop."
readme = "README.md"
repository = "https://github.com/OpenByteDev/transparent" 
documentation = "https://docs.rs/transparent"
license = "MIT"
authors = ["OpenByte <development.openbyte@gmail.com>"]
edition = "2018"
build = "build.rs"
keywords = ["headless", "hidden", "process", "virtual", "desktop"]

[target.'cfg(windows)'.dependencies]
tempfile = "3.2"

[target.'cfg(windows)'.build-dependencies]
build-target = "0.3"
cargo-emit = "0.2"
zip = "0.5"
gitignore = "1.0"
path-absolutize = "3.0"
walkdir = "2.3"

[package.metadata.docs.rs]
targets = ["x86_64-pc-windows-msvc", "x86_64-unknown-linux-gnu", "x86_64-apple-darwin"]
